export const roles = [
  { title: 'Backend Developer', group: 'Development', value: 'backend' },
  { title: 'Product Manager', group: 'Management', value: 'product manager' },
  { title: 'Frontend Developer', group: 'Development', value: 'frontend' },
  { title: 'Data Scientist', group: 'Data', value: 'data scientist' },
  { title: 'UI/UX Designer', group: 'Design', value: 'ui/ux designer' },
  { title: 'Software Engineer', group: 'Development', value: 'software engineer' },
  { title: 'Database Administrator', group: 'Data', value: 'database administrator' },
  { title: 'Project Manager', group: 'Management', value: 'project manager' },
  { title: 'Systems Analyst', group: 'Development', value: 'systems analyst' },
  { title: 'Full Stack Developer', group: 'Development', value: 'full stack developer' },
  { title: 'Technical Lead', group: 'Management', value: 'technical lead' },
  { title: 'Scrum Master', group: 'Management', value: 'scrum master' },
  { title: 'Quality Assurance Engineer', group: 'Testing', values: 'quality assurance engineer' },
  { title: 'DevOps Engineer', group: 'Development', value: 'devops engineer' },
  { title: 'Data Engineer', group: 'Data', value: 'data engineer' },
  { title: 'Machine Learning Engineer', group: 'Data', value: 'machine learning engineer' },
  { title: 'Cybersecurity Analyst', group: 'Security', value: 'cybersecurity analyst' },
  { title: 'Cloud Architect', group: 'Infrastructure', value: 'cloud architect' },
  { title: 'Network Engineer', group: 'Infrastructure', value: 'network engineer' },
  { title: 'Business Analyst', group: 'Management', value: 'business analyst' },
  { title: 'UI Designer', group: 'Design', value: 'ui designer' },
  { title: 'Backend Engineer', group: 'Development', value: 'backend engineer' },
  { title: 'Frontend Engineer', group: 'Development', value: 'frontend engineer' },
  { title: 'Product Owner', group: 'Management', value: 'product owner' },
  { title: 'Software Architect', group: 'Development', value: 'software architect' },
  { title: 'Technical Writer', group: 'Documentation', value: 'technical writer' },
  { title: 'System Administrator', group: 'Infrastructure', value: 'system administrator' },
  { title: 'UX Designer', group: 'Design', value: 'ux designer' },
  { title: 'QA Engineer', group: 'Testing', value: 'qa engineer' },
  { title: 'Web Developer', group: 'Development', value: 'web developer' },
  { title: 'IT Manager', group: 'Management', value: 'it manager' },
  { title: 'Database Developer', group: 'Data', value: 'database developer' },
  { title: 'Technical Consultant', group: 'Consulting', value: 'technical consultant' },
  { title: 'IT Specialist', group: 'Infrastructure', value: 'it specialist' },
]

export const experience = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
]

export const pay = [
  { label: '20L', value: 20 },
  { label: '30L', value: 30 },
  { label: '40L', value: 40 },
  { label: '50L', value: 50 },
  { label: '60L', value: 60 },
  { label: '70L', value: 70 },
  { label: '80L', value: 80 },
]
